### ISSUE TITLE
Unable to get this working with old or new iTunes (Windows 10)

### ISSUE THREAD

**Issue by Casuallynoted** [qdot/reztunes#1]
Hello! I've been looking to try to see about using this for feeling sound vibration inside of VR applications like Tilt Brush. I have the plugin installed in the correct folder and have tried to get it working with both old and new version of itunes, 32 and 64 bit. It does show up in the visualizers menu, but when I have music playing the Trance Vibrator doesn't vibrate. It also flashes gray whether it's plugged in or not. Is there any way I may be able to fix this?

**Comment by qdot** [comment]
Ok. Wow. Hi. 

Soooooooooooo notice the last commit on this is from 11 years ago. Technically, this repo should be archived. This code barely worked in 2008, and absolutely will not work now. I can guarantee that.

Now, that said, if you'd like help getting sound to vibration or other output working, I can definitely help you with that. I run another project, at https://buttplug.io (and our github is at https://github.com/buttplugio) that is made for controlling modern hardware (or it'll even work with the trancevibrator if you somehow have one of those, though that doesn't work on Windows 10). 

I'm gonna close this bug 'cause it's definitely a WONTFIX here, but if you'd like to talk more about how to get this going, I've got a message board at https://metafetish.club, a discord at https://discord.buttplug.io, or you can just DM me on twitter at https://twitter.com/qdot.
